import { sendResponse } from '../../lib/vercel.mjs';

export default function handler(req, res) {
  return sendResponse(res, new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Qiyue Gateway Usage</title><style>
  body{font:15px system-ui,sans-serif;background:#0b1020;color:#e8edf7;margin:0;padding:32px}main{max-width:1100px;margin:auto}input,button,select{background:#151d32;color:inherit;border:1px solid #33415f;border-radius:8px;padding:10px 12px}button{cursor:pointer;background:#c9a866;color:#101522;border:0;font-weight:700}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card{background:#121a2d;border:1px solid #263451;border-radius:12px;padding:16px}.value{font-size:25px;font-weight:700;margin-top:8px}.muted{color:#9ba8bd}.error{color:#ff9d9d;margin-top:12px}table{width:100%;border-collapse:collapse;margin-top:20px;background:#121a2d}th,td{text-align:left;padding:10px;border-bottom:1px solid #263451;font-size:13px}th{color:#c9a866}</style></head><body><main>
  <h1>Qiyue Gateway Usage</h1><p class="muted">Request metadata only. Prompts and model responses are not stored.</p>
  <div class="toolbar"><input id="token" type="password" placeholder="Admin token" size="28"><select id="days"><option value="1">Today</option><option value="7">7 days</option><option value="30" selected>30 days</option><option value="90">90 days</option></select><button id="load">Load usage</button></div><div id="error" class="error"></div><section id="cards" class="cards"></section>
  <h2>App breakdown</h2><table><thead><tr><th>App</th><th>Requests</th><th>Request share</th><th>Tokens</th><th>Token share</th><th>Errors</th><th>Estimated cost</th></tr></thead><tbody id="summary"></tbody></table>
  <h2>Recent requests</h2><table><thead><tr><th>Time</th><th>App</th><th>Model</th><th>Provider</th><th>Tokens</th><th>Latency</th><th>Status</th></tr></thead><tbody id="rows"></tbody></table></main>
  <script>
  const token=document.querySelector('#token');const saved=localStorage.getItem('qiyue_gateway_admin_token');if(saved)token.value=saved;const fmt=n=>Number(n||0).toLocaleString();
  async function load(){const err=document.querySelector('#error');err.textContent='';localStorage.setItem('qiyue_gateway_admin_token',token.value);const r=await fetch('/api/admin/usage?days='+document.querySelector('#days').value,{headers:{Authorization:'Bearer '+token.value}});const d=await r.json();if(!r.ok){err.textContent=d.error?.message||'Failed to load';return}const s=d.summary.reduce((a,x)=>({requests:a.requests+Number(x.requests),tokens:a.tokens+Number(x.total_tokens),errors:a.errors+Number(x.errors),cost:a.cost+Number(x.estimated_cost_usd||0)}),{requests:0,tokens:0,errors:0,cost:0});document.querySelector('#cards').innerHTML=[['Requests',fmt(s.requests)],['Total tokens',fmt(s.tokens)],['Errors',fmt(s.errors)],['Estimated cost',s.cost?'$'+s.cost.toFixed(4):'Not configured']].map(x=>'<div class="card"><div class="muted">'+x[0]+'</div><div class="value">'+x[1]+'</div></div>').join('');document.querySelector('#summary').innerHTML=d.summary.map(x=>'<tr><td>'+x.project+'</td><td>'+fmt(x.requests)+'</td><td>'+x.request_share_percent+'%</td><td>'+fmt(x.total_tokens)+'</td><td>'+x.token_share_percent+'%</td><td>'+fmt(x.errors)+'</td><td>'+(Number(x.estimated_cost_usd||0)?'$'+Number(x.estimated_cost_usd).toFixed(4):'—')+'</td></tr>').join('')||'<tr><td colspan="7">No usage yet</td></tr>';document.querySelector('#rows').innerHTML=d.recent.map(x=>'<tr><td>'+new Date(x.created_at).toLocaleString()+'</td><td>'+x.project+'</td><td>'+(x.requested_model||'—')+'</td><td>'+(x.provider||'—')+'</td><td>'+fmt(x.total_tokens)+'</td><td>'+fmt(x.latency_ms)+' ms</td><td>'+x.status+' ('+x.status_code+')</td></tr>').join('')||'<tr><td colspan="7">No usage yet</td></tr>'}document.querySelector('#load').onclick=load;
  </script></body></html>`, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' } }));
}
