import { sendResponse } from '../../lib/vercel.mjs';

export default function handler(req, res) {
  return sendResponse(res, new Response(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Qiyue Gateway Usage</title><style>
  :root{color-scheme:dark}*{box-sizing:border-box}body{font:14px/1.45 system-ui,-apple-system,sans-serif;background:#090e1c;color:#e9edf7;margin:0;padding:28px}main{max-width:1240px;margin:auto}.top{display:flex;justify-content:space-between;align-items:end;gap:18px;margin-bottom:22px}h1{font-size:28px;margin:0}h2{font-size:17px;margin:28px 0 12px}.muted{color:#94a1b8}.toolbar{display:flex;gap:9px;flex-wrap:wrap;margin:18px 0}input,button,select{background:#141d31;color:inherit;border:1px solid #2c3b5d;border-radius:9px;padding:10px 12px}input{min-width:250px}button{cursor:pointer;background:#d2ad67;color:#101522;border:0;font-weight:700}.error{color:#ff9c9c;margin:10px 0}.cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.card,.panel{background:#111a2d;border:1px solid #233250;border-radius:14px}.card{padding:17px}.card .label{color:#94a1b8}.value{font-size:25px;font-weight:750;margin-top:7px}.panel{padding:18px}.grid2{display:grid;grid-template-columns:1.25fr .75fr;gap:14px}.chart{height:210px;display:flex;align-items:end;gap:8px;padding:20px 8px 28px;border-bottom:1px solid #2a3958;overflow:hidden}.barwrap{height:100%;flex:1;min-width:18px;display:flex;flex-direction:column;justify-content:end;align-items:center;gap:5px}.bar{width:100%;max-width:36px;min-height:2px;background:#d2ad67;border-radius:5px 5px 0 0}.bar.blue{background:#78b9df}.barwrap small{color:#8190a8;font-size:10px;white-space:nowrap;transform:rotate(-25deg)}.legend{color:#9ba8bd;margin-top:10px}.legend i{display:inline-block;width:9px;height:9px;background:#d2ad67;border-radius:50%;margin-right:5px}.legend i.blue{background:#78b9df;margin-left:15px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 9px;border-bottom:1px solid #263451;white-space:nowrap}th{color:#d2ad67;font-weight:650}tbody tr:hover{background:#16213a}.table-scroll{overflow:auto}.empty{color:#8d9bb2;padding:18px 0}@media(max-width:800px){body{padding:16px}.top{display:block}.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.grid2{grid-template-columns:1fr}.value{font-size:21px}}
  </style></head><body><main><div class="top"><div><h1>Qiyue Gateway Usage</h1><div class="muted">按应用、模型和时间查看网关用量；不保存提示词或模型回复。</div></div></div>
  <div class="toolbar"><input id="token" type="password" placeholder="Admin token"><select id="days"><option value="1">今天</option><option value="7">近 7 天</option><option value="30" selected>近 30 天</option><option value="90">近 90 天</option></select><select id="project"><option value="">全部应用</option><option value="qiyue-web">QiYue Web</option><option value="todoai">TodoAI</option><option value="ios">iOS</option></select><select id="model"><option value="">全部模型</option><option value="qy-fast">qy-fast</option><option value="qy-smart">qy-smart</option><option value="qy-gemini">qy-gemini</option><option value="qy-qwen">qy-qwen</option><option value="qy-deepseek">qy-deepseek</option></select><button id="load">加载用量</button></div><div id="error" class="error"></div>
  <section id="cards" class="cards"></section><h2>用量趋势</h2><section class="grid2"><div class="panel"><strong>每日 Token</strong><div id="tokenChart" class="chart"></div><div class="legend"><i></i>总 token <span class="muted">按所选时间范围</span></div></div><div class="panel"><strong>每日请求</strong><div id="requestChart" class="chart"></div><div class="legend"><i class="blue"></i>API 请求次数</div></div></section>
  <h2>应用占比</h2><div class="panel table-scroll"><table><thead><tr><th>应用</th><th>请求数</th><th>请求占比</th><th>Token</th><th>Token 占比</th><th>错误</th><th>预计花费</th></tr></thead><tbody id="summary"></tbody></table></div>
  <h2>模型用量</h2><div class="panel table-scroll"><table><thead><tr><th>模型</th><th>供应商</th><th>请求数</th><th>输入 Token</th><th>输出 Token</th><th>总 Token</th><th>预计花费</th></tr></thead><tbody id="models"></tbody></table></div>
  <h2>最近请求</h2><div class="panel table-scroll"><table><thead><tr><th>时间</th><th>应用</th><th>模型</th><th>供应商</th><th>Token</th><th>耗时</th><th>状态</th></tr></thead><tbody id="rows"></tbody></table></div></main>
  <script>
  const token=document.querySelector('#token');const saved=localStorage.getItem('qiyue_gateway_admin_token');if(saved)token.value=saved;const fmt=n=>Number(n||0).toLocaleString();const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function money(n){return Number(n||0)?'$'+Number(n).toFixed(4):'—'}
  function chart(target,items,key,klass){const el=document.querySelector(target);const max=Math.max(1,...items.map(x=>Number(x[key]||0)));el.innerHTML=items.length?items.map(x=>'<div class="barwrap" title="'+fmt(x[key])+'"><div class="bar '+klass+'" style="height:'+Math.max(2,Number(x[key]||0)/max*100)+'%"></div><small>'+esc(x.day.slice(5))+'</small></div>').join(''):'<div class="empty">暂无数据</div>'}
  async function load(){const err=document.querySelector('#error');err.textContent='';localStorage.setItem('qiyue_gateway_admin_token',token.value);const params=new URLSearchParams({days:document.querySelector('#days').value});if(document.querySelector('#project').value)params.set('project',document.querySelector('#project').value);if(document.querySelector('#model').value)params.set('model',document.querySelector('#model').value);const r=await fetch('/api/admin/usage?'+params,{headers:{Authorization:'Bearer '+token.value}});const d=await r.json();if(!r.ok){err.textContent=d.error?.message||'加载失败';return}const s=d.summary.reduce((a,x)=>({requests:a.requests+Number(x.requests),tokens:a.tokens+Number(x.total_tokens),errors:a.errors+Number(x.errors),cost:a.cost+Number(x.estimated_cost_usd||0)}),{requests:0,tokens:0,errors:0,cost:0});document.querySelector('#cards').innerHTML=[['API 请求',fmt(s.requests)],['总 Token',fmt(s.tokens)],['错误请求',fmt(s.errors)],['预计花费',s.cost?'$'+s.cost.toFixed(4):'未配置价格']].map(x=>'<div class="card"><div class="label">'+x[0]+'</div><div class="value">'+x[1]+'</div></div>').join('');chart('#tokenChart',d.daily,'total_tokens','');chart('#requestChart',d.daily,'requests','blue');document.querySelector('#summary').innerHTML=d.summary.map(x=>'<tr><td>'+esc(x.project)+'</td><td>'+fmt(x.requests)+'</td><td>'+x.request_share_percent+'%</td><td>'+fmt(x.total_tokens)+'</td><td>'+x.token_share_percent+'%</td><td>'+fmt(x.errors)+'</td><td>'+money(x.estimated_cost_usd)+'</td></tr>').join('')||'<tr><td colspan="7" class="empty">暂无数据</td></tr>';document.querySelector('#models').innerHTML=d.byModel.map(x=>'<tr><td>'+esc(x.requested_model)+'</td><td>'+esc(x.provider)+'</td><td>'+fmt(x.requests)+'</td><td>'+fmt(x.prompt_tokens)+'</td><td>'+fmt(x.completion_tokens)+'</td><td>'+fmt(x.total_tokens)+'</td><td>'+money(x.estimated_cost_usd)+'</td></tr>').join('')||'<tr><td colspan="7" class="empty">暂无数据</td></tr>';document.querySelector('#rows').innerHTML=d.recent.map(x=>'<tr><td>'+new Date(x.created_at).toLocaleString()+'</td><td>'+esc(x.project)+'</td><td>'+esc(x.requested_model)+'</td><td>'+esc(x.provider)+'</td><td>'+fmt(x.total_tokens)+'</td><td>'+fmt(x.latency_ms)+' ms</td><td>'+esc(x.status)+' ('+x.status_code+')</td></tr>').join('')||'<tr><td colspan="7" class="empty">暂无数据</td></tr>'}document.querySelector('#load').onclick=load;
  </script></body></html>`, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' } }));
}
